### PR TITLE
Add i18n and vector logo

### PR DESCRIPTION
**Pull request by SNDST00M**
<p align="center"></p>

### CODE REVIEW

**Comment by SNDST00M** [comment]
Adding `htmlTree`, requiring MATLAB R2018b and the Text Analytics Toolbox.
It will be added through an `exists` compatibility layer.

**Comment by SNDST00M** [comment]
@mobeets ready for merging - you'll like this!

**Comment by SNDST00M** [comment]
Hope you can carve some time from your weekend to review this.
I'm buying a copy of MATLAB and some engineering toolboxes next week
We can use my license to make a CI workflow, but I will need maintainer permissions.

**Comment by mobeets** [comment]
Is this passing all the tests in test/test_install for you? For me (R2015a), I had to make a change (to line 1243) to get it running, and then it broke on the first install (of export_fig).

The error for this one happens on line 584, because package.url is
'https://www.mathworks.com/matlabcentral/fileexchange/matlabcentral/fileexchange/23629-export_fig?s_tid=srchtitle&download=true%3Fdownload=true' (with HTTP response code 404).'

Also, is it possible to handle pre-existing versions of 'mpm.mat'? Are the differences between the previous and proposed version of mpm.mat just in the names of variables? It would be nice not to have to reinstall all of my packages in mpm-packages.

**Comment by SNDST00M** [comment]
The URL should work in R2015a now.
I understand that `mpm.mat` is now going to use camel-case?
The difference is that any variable names `like_this` will now look `likeThis`.

**Comment by SNDST00M** [comment]
@mobeets hopefully this resolves the issue:

https://github.com/mobeets/mpm/blob/1ccb57ee79063102c95677d3d87db3103c8d4478/mpm.m#L665-L687

**Comment by SNDST00M** [comment]
Any updates on when this could be merged? Also would you like free CI as a Github Action?

**Comment by SNDST00M** [comment]
Bumping this for September. Any blockers still?

**Comment by mobeets** [comment]
Can you update the mpm.m and test_install.m from the update below? I ran into a few bugs to get everything to work.

- line 1243 in the current mpm.m crashed entirely; needed to be split into two lines before calling sprintf
- error getting correct url when no htmlTree
- no "contains" < 2016
- 
[update.zip](https://github.com/mobeets/mpm/files/7230262/update.zip)

**Comment by SNDST00M** [comment]
Passes in R2021a.

**Comment by mobeets** [comment]
Awesome, looks great now!

**Comment by SNDST00M** [comment]
The logo needs updating at https://uk.mathworks.com/matlabcentral/fileexchange/54548-mpm !

**Pull request merged**
