### PR TITLE
Adopt official REST API

### LINKED ISSUE #84: Use new Matlab Central API for File Exchange query
A query with `scope=file-exchange` allows us to search for MATLAB scripts.
See documentation at [https://api.mathworks.com](https://api.mathworks.com/).

### PR DESCRIPTION
**Pull request by zm-cttae**
Fixes #84.
Replace HTML parsing from #75 with the official REST API for Mathworks Central.

### CODE REVIEW

**Comment by mobeets** [comment]
Hi, thanks so much for submitting this! Could you please run `test/test_install.m` and confirm that everything runs fine? Then let me know and I can merge this in

**Comment by zm-cttae** [comment]
Search result changed, updated it and its now passing ✅

**Comment by zm-cttae** [comment]
There's also a logo that hasn;t been uploaded to the [File Exchange](https://www.mathworks.com/matlabcentral/fileexchange/54548-mpm).. did you want to adopt it or use a different design?

**Comment by mobeets** [comment]
Just fixed it

**Pull request merged**
